use_frameworks!
platform :ios, '9.3'

target 'NSelectViewCheckBox_Example' do
  pod 'NSelectViewCheckBox', :path => '../'
  
  pod 'NSelect', :git => 'https://github.com/fitsyu/NSelect.git'
  pod 'UIRadioButton', :git => 'https://github.com/fitsyu/UIRadioButton.git'

  pod 'UICheckbox.Swift', :git => 'https://github.com/fitsyu/UICheckbox.Swift.git'

  
  target 'NSelectViewCheckBox_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    
  end
end
